---
# This playbook bootstraps an Intel Edison with base settings

- hosts: edisons
  user: root
  pre_tasks:
#  - name: be sure libselinux-python are installed
#    yum: >
#      name=libselinux-python
#      state=present
#    when: ansible_os_family == "RedHat"

  roles:
    - opkg-edison
    - journald
  tasks:
    ## TODO: Ensure that packages are of latest version (or version we build against)
    ##  - mraa 0.7.5.60
    ##  - upm 0.4.1
    ##  - oobe 1.2.0-r0
    ##  - xdk-daemon 0.0.35-r0 # (dev only)
    ## TODO: Fix terminal size issue when using serial console: stty rows 46 cols 300
    - name: Upgrade Intel packages
      opkg: >
        name={{ item }}
        state=installed
      with_items:
        - upm
        - mraa
        - oobe
      tags:
        - opkg_upgrade
        - packages
        - upgrade_packages
