namespace: lyraphase
name: opnsense
version: 0.0.1
readme: README.md
authors:
  - James Cuzella <james.cuzella@lyraphase.com>

description: LyraPhase OPNsense Ansible collection allows automation, and
  orchestration of OPNsense firewall configuration, package installation, and
  firmware updates.

license_file: LICENSE

tags: ["opnsense", "infrastructure", "automation", "devops"]

dependencies:
  {
    "community.general": ">=10.6.0",
    "ansibleguy.opnsense": ">=1.2.13",
    "ansible.netcommon": ">=8.1.0",
    "ansible.utils": ">=6.0.0",
  }

repository: https://github.com/LyraPhase/ansible_opnsense

homepage: https://github.com/LyraPhase/ansible_opnsense

issues: https://github.com/LyraPhase/ansible_opnsense/issues

documentation: https://github.com/LyraPhase/ansible_opnsense/tree/docs

build_ignore:
  - .github
  - codecov.yml
  - tests/integration
  - tests/sanity
  - tests/unit
  - tests/config.yml
  - test-requirements.txt
  - tox-ansible.ini
  - changelogs
