---
# openwrt-base: entry point for meta
galaxy_info:
  author: James Cuzella
  description: Installs python and Ansible dependencies via opkg on OpenWRT / LEDE
  company: LyraPhase
  license: MIT
  min_ansible_version: 2.5
  # Platforms tested are uncommented, but it probably works on most CentOS/RHEL
  platforms:
    - name: Openwrt
      versions:
        - 17.01
  galaxy_tags:
    - system
    - networking
    - openwrt
  categories:
  #   - web
    - system
    - packaging
  #   - networking
  #   - monitoring
  #   - development
  #   - database:sql
  #   - database:nosql
  #   - database
  #   - clustering
  #   - cloud:rax
  #   - cloud:gce
  #   - cloud:ec2
  #   - cloud
  dependencies:
  # Specify role dependencies here
  # For foo
  #  - foo
# version: 0.0.1 ## Ansible 2.0 broke this. Uncomment if / when they ever fix ansible/ansible#13496
