---
version: 3

images:
 base_image:
  name: quay.io/centos/centos:stream10-minimal
options:
  package_manager_path: /usr/bin/microdnf


dependencies:
  python_interpreter:
    package_system: python3.12
    python_path: /usr/bin/python3.12
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python: ee/ee-requirements.txt
  system: ee/ee-bindep.txt
  galaxy: requirements.yml
additional_build_files:
  - src: ee/profile.d/00-xdg-docker-config.sh
    dest: profile.d
  - src: ee/profile.d/p10k-centos.zsh
    dest: profile.d
  - src: ee/profile.d/bat-themes.sh
    dest: profile.d
  - src: ee/profile.d/zsh-profile.sh
    dest: profile.d
additional_build_steps:
  append_base:
    - RUN $PKGMGR install -y --nodocs --setopt install_weak_deps=0
          git-core git-lfs && $PKGMGR clean all
    - RUN $PYCMD -m pip install --no-cache-dir -U pip &&
          $PYCMD -m pip cache purge
  append_final: |
    RUN sed -i -e 's/^Defaults.*requiretty/Defaults    !requiretty/' \
               -e 's/^%wheel.*ALL$/%wheel    ALL=(ALL)    NOPASSWD: ALL/' /etc/sudoers
    RUN $PKGMGR install -y --nodocs --setopt install_weak_deps=0 lastpass-cli && \
        rpm -e --nodeps xclip && \
        $PKGMGR remove -y libX11 libX11-common libXmu libXext libXt && \
        $PKGMGR clean all
    RUN gem install --no-document lastpass-ansible
    RUN update-crypto-policies --set LEGACY
    COPY _build/profile.d/00-xdg-docker-config.sh /etc/profile.d/00-xdg-docker-config.sh
    RUN export _docker_xdg_cache_home=/var/run/user/docker-skel/cache && \
        echo "$_docker_xdg_cache_home" && \
        mkdir -p "$_docker_xdg_cache_home" && \
        mkdir -p "${_docker_xdg_cache_home}/zsh/zcompcache" && \
        chown -R 1000:1000 "$_docker_xdg_cache_home" && \
        chmod 0700 "$_docker_xdg_cache_home"
    RUN git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git /usr/share/oh-my-zsh && \
        cp /usr/share/oh-my-zsh/templates/zshrc.zsh-template /usr/share/oh-my-zsh/zshrc && \
        curl -Ls -o - 'https://raw.githubusercontent.com/manjaro-sway/oh-my-zsh/refs/heads/master/0001-zshrc.patch' \
          | patch -p1 /usr/share/oh-my-zsh/zshrc && \
        git config --global --add safe.directory /usr/share/oh-my-zsh
    RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /usr/share/zsh-theme-powerlevel10k && \
        cd /usr/share/zsh-theme-powerlevel10k && \
        sed -i'' -e '/_p9k_must_init() {/a \ \ [ -r "$CENTOS_POWERLEVEL9K_CONFIG_FILE" ] && builtin source "$CENTOS_POWERLEVEL9K_CONFIG_FILE"' \
          /usr/share/zsh-theme-powerlevel10k/internal/p10k.zsh && \
          sync /usr/share/zsh-theme-powerlevel10k/internal/p10k.zsh && \
          export GITSTATUS_CACHE_DIR=/var/run/user/docker-skel/cache/gitstatus && \
          /usr/share/zsh-theme-powerlevel10k/gitstatus/install && \
          chown -R 1000:1000 "${GITSTATUS_CACHE_DIR}" && \
        for file in *.zsh-theme internal/*.zsh gitstatus/*.zsh gitstatus/install; do \
          zsh -fc "emulate zsh -o no_aliases && zcompile -R -- $file.zwc $file" ; \
          sync ${file}.zwc ; \
        done && \
        export ZSH_COMPDUMP="/var/run/user/docker-skel/cache/zsh/zcompcache/.zcompdump-$(zsh -c 'echo -n ${ZSH_VERSION}')" && \
        export XDG_CACHE_HOME=/var/run/user/docker-skel/cache && \
        zsh -l -i -c 'echo "Generating $ZSH_COMPDUMP" && source /usr/share/oh-my-zsh/zshrc && sync "$ZSH_COMPDUMP"' && \
        chown -R 1000:1000 "$(dirname "${ZSH_COMPDUMP}")" && touch "${ZSH_COMPDUMP}".zwc && \
        git config --global --add safe.directory /usr/share/zsh-theme-powerlevel10k
    COPY _build/profile.d/p10k-centos.zsh /etc/profile.d/p10k-centos.zsh
    COPY _build/profile.d/zsh-profile.sh /etc/profile.d/zsh-profile.sh
    RUN echo '[[ ! -f /etc/profile.d/p10k-centos.zsh ]] || source /etc/profile.d/p10k-centos.zsh' >> \
        /usr/share/oh-my-zsh/zshrc
    RUN echo '[[ ! -f /etc/profile ]] || source /etc/profile' >> \
        /usr/share/oh-my-zsh/zshrc
    COPY _build/profile.d/bat-themes.sh /etc/profile.d/bat-themes.sh
    RUN mkdir -p /run/user/docker-skel/cache/bat && \
        echo 'export BAT_CACHE_PATH=/run/user/$(id -u)/cache/bat' > /etc/profile.d/bat-cache.sh && \
        export BAT_CACHE_PATH=/run/user/docker-skel/cache/bat && \
        bat cache --build && \
        chmod 0775 /run/user/docker-skel/cache/bat && \
        chown -R 1000:users /run/user/docker-skel/cache/bat && \
        chmod 0664 /run/user/docker-skel/cache/bat/*
    RUN rpm -i 'https://dl.fedoraproject.org/pub/fedora/linux/updates/42/Everything/x86_64/Packages/f/foot-terminfo-1.24.0-1.fc42.x86_64.rpm'
    RUN rpm -i 'https://dl.fedoraproject.org/pub/fedora/linux/updates/42/Everything/x86_64/Packages/g/git-delta-0.18.2-9.fc42.x86_64.rpm'
    ARG TERRA_RELEASEVER=42
    RUN rpm -i 'https://repos.fyralabs.com/terra42/eza-0%3A0.23.4-1.fc42.x86_64.rpm' && \
        $PKGMGR clean all
    RUN $PYCMD -m pip install --no-cache-dir pre-commit
