---
version: 3

images:
 base_image:
  name: quay.io/centos/centos:stream10-minimal
options:
  package_manager_path: /usr/bin/microdnf


dependencies:
  python_interpreter:
    package_system: python3.12
    python_path: /usr/bin/python3.12
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python: ee/ee-requirements.txt
  system: ee/ee-bindep.txt
  galaxy: requirements.yml
  exclude:
    system:
      - systemd
      - libX11
      - libX11-common
      - libXmu
      - python3-devel
      - python3-libs
      - python39-devel
      - python38-pytz
      - python38-requests
      - python38-pyyaml
      - python38-cryptography
      - python38-devel
      - python38-requests
additional_build_files:
  - src: ee/profile.d/p10k-centos.zsh
    dest: profile.d
  - src: ee/profile.d/bat-themes.sh
    dest: profile.d
additional_build_steps:
  append_base:
    - RUN $PKGMGR install -y git-core git-lfs
    - RUN $PYCMD -m pip install -U pip
  append_final: |
    RUN sed -i -e 's/^Defaults.*requiretty/Defaults    !requiretty/' \
               -e 's/^%wheel.*ALL$/%wheel    ALL=(ALL)    NOPASSWD: ALL/' /etc/sudoers
    RUN $PKGMGR install -y lastpass-cli && \
        rpm -e --nodeps xclip && \
        $PKGMGR remove -y libX11 libX11-common libXmu libXext libXt
    RUN gem install --no-document lastpass-ansible
    RUN git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git /usr/share/oh-my-zsh && \
        cp /usr/share/oh-my-zsh/templates/zshrc.zsh-template /usr/share/oh-my-zsh/zshrc && \
        curl -Ls -o - 'https://raw.githubusercontent.com/manjaro-sway/oh-my-zsh/refs/heads/master/0001-zshrc.patch' \
          | patch -p1 /usr/share/oh-my-zsh/zshrc
    RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /usr/share/zsh-theme-powerlevel10k \
        && cd /usr/share/zsh-theme-powerlevel10k && \
        for file in *.zsh-theme internal/*.zsh gitstatus/*.zsh gitstatus/install; do \
          zsh -fc "emulate zsh -o no_aliases && zcompile -R -- $file.zwc $file" ; \
        done
    COPY _build/profile.d/p10k-centos.zsh /etc/profile.d/p10k-centos.zsh
    RUN echo '[[ ! -f /etc/profile.d/p10k-centos.zsh ]] || source /etc/profile.d/p10k-centos.zsh' >> \
        /usr/share/oh-my-zsh/zshrc
    RUN echo '[[ ! -f /etc/profile ]] || source /etc/profile' >> \
        /usr/share/oh-my-zsh/zshrc
    COPY _build/profile.d/bat-themes.sh /etc/profile.d/bat-themes.sh
    RUN mkdir -p /run/user/bat/cache && \
        echo 'export BAT_CACHE_PATH=/run/user/bat/cache' > /etc/profile.d/bat-cache.sh && \
        export BAT_CACHE_PATH=/run/user/bat/cache && \
        bat cache --build && \
        chmod 0775 /run/user/bat/cache && \
        chown -R root:users /run/user/bat/cache && \
        chmod 0664 /run/user/bat/cache/*
    RUN /bin/sh -c 'for cmd in ps top free pgrep pidof pkill pmap pwdx \
            uptime w watch ; do \
            update-alternatives --verbose --install /usr/bin/$cmd $cmd /usr/sbin/busybox 50 ; \
          done'
    RUN for cmd in sysctl ; do \
            update-alternatives --verbose --install /usr/sbin/$cmd $cmd /usr/sbin/busybox 50 ; \
          done
