---
version: 3

images:
 base_image:
   name: quay.io/ansible/awx-ee:latest

dependencies:
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python: ee/ee-requirements.txt
  system: ee/ee-bindep.txt
  galaxy: requirements.yml

additional_build_steps:
  append_final: |
    RUN sed -i -e 's/^Defaults.*requiretty/Defaults    !requiretty/' \
               -e 's/^%wheel.*ALL$/%wheel    ALL=(ALL)    NOPASSWD: ALL/' /etc/sudoers
    RUN dnf install -y lastpass-cli && \
        rpm -e --nodeps xclip && \
        dnf remove -y libX11 libX11-common
    RUN gem install --no-document lastpass-ansible