---
version: 3

images:
 base_image:
  name: quay.io/centos/centos:stream10-minimal
options:
  package_manager_path: /usr/bin/microdnf


dependencies:
  python_interpreter:
    package_system: python3.12
    python_path: /usr/bin/python3.12
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python: ee/ee-requirements.txt
  system: ee/ee-bindep.txt
  galaxy: requirements.yml

additional_build_steps:
  append_final: |
    RUN sed -i -e 's/^Defaults.*requiretty/Defaults    !requiretty/' \
               -e 's/^%wheel.*ALL$/%wheel    ALL=(ALL)    NOPASSWD: ALL/' /etc/sudoers
    RUN $PKGMGR install -y lastpass-cli && \
        rpm -e --nodeps xclip && \
        $PKGMGR remove -y libX11 libX11-common libXmu libXext libXt
    RUN gem install --no-document lastpass-ansible
