---
#roles:
collections:
  # OPNSense requirements
  - name: ansibleguy.opnsense
  - name: community.general
  - name: https://github.com/trinitronx/ansible_managemynetwork.git
    type: git
    version: fix-broken-conditionals-ansible-deprecation
#  - name: imp1sh.ansible_managemynetwork
