---
#roles:
collections:
  - name: ansible.posix
  # OPNSense requirements
  - name: ansibleguy.opnsense
  - name: community.general
  - name: https://github.com/trinitronx/ansible_managemynetwork.git
    type: git
    version: lede
  - name: ansible.netcommon
#  - name: imp1sh.ansible_managemynetwork
