---
# openwrt-dumbap-base: Tasks entry point. Called by main.yml

# Load a variable file based on the OS type, or a default if not found.
- name: Include vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: openwrt_dumbap_logrotate_files is not defined

- name: Install logrotate drop-ins
  ansible.builtin.copy:
    src: files/logrotate.d/{{ item }}
    dest: /etc/logrotate.d/{{ item }}
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ openwrt_dumbap_logrotate_files }}"
