---
openwrt_dhcp_poolshost:
  - name: "wan"
    ignore: "1"
    interface: "wan"
  - name: "lan"
    ignore: "1"
    interface: "lan"
    start: "100"
    limit: "150"
    leasetime: "12h"
    dhcpv4: "server"
    dhcpv6: "server"
    ra: "hybrid"
    ra_default: "0"
    ra_flags:
      - "managed-config"
      - "other-config"
#    domain:
#      - "example.com"
#    dhcp_option:
#      - "6,10.10.133.111"
#    dns:
#      - "2620:fe::fe"
#      - "2620:fe::fe:9"
# dnsmasq global options
openwrt_dhcp_dnsmasq_domainneeded: '1'
openwrt_dhcp_dnsmasq_localise_queries: '1'
openwrt_dhcp_dnsmasq_rebind_protection: '1'
openwrt_dhcp_dnsmasq_rebind_localhost: '1'
openwrt_dhcp_dnsmasq_local: '/lan/'
openwrt_dhcp_dnsmasq_domain: 'lan'
openwrt_dhcp_dnsmasq_leasefile: '/tmp/dhcp.leases'
openwrt_dhcp_dnsmasq_resolvfile: '/tmp/resolv.conf.d/resolv.conf.auto'
openwrt_dhcp_dnsmasq_localservice: '1'
openwrt_dhcp_dnsmasq_cachesize: '1000'
openwrt_dhcp_dnsmasq_ednspacket_max: '1232'
