## If you want to use one of the kitchen-docker* drivers...
## You should rename this file to: .kitchen.local.yml
## Hint: Make sure you have kitchen-docker and kitchen-docker-api gems installed
## Then set DOCKER_HOST=tcp://my-docker-host.example.com:4243
---
## driver name: docker is for portertech/kitchen-docker
driver:
  name: docker
<% unless ENV['KITCHEN_HTTP_PROXY'].nil? %>
  http_proxy: <%= ENV['KITCHEN_HTTP_PROXY'] %>
  links: "polipo:polipo"
<% end %>
<% unless ENV['KITCHEN_HTTP_PROXY'].nil? && ENV['KITCHEN_HTTPS_PROXY'].nil? %>
  https_proxy: <%= ENV['KITCHEN_HTTPS_PROXY'].nil? ? ENV['KITCHEN_HTTP_PROXY'] : ENV['KITCHEN_HTTPS_PROXY'] %>
<% end %>

## driver_plugin: docker is for adnichols/kitchen-docker-api
#driver_plugin: docker

driver_config:
  hostname: kitchen
  use_sudo: true
  socket: <%= ENV['DOCKER_HOST'] || 'unix:///var/run/docker.sock' %>
  #  socket: tcp://localhost:4243
  require_chef_omnibus: false
  provision_command: &1
    - curl -L http://www.opscode.com/chef/install.sh | bash
    - curl -L https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh | bash

provisioner:
  require_chef_omnibus: false
<% unless ENV['KITCHEN_HTTP_PROXY'].nil? && ENV['KITCHEN_HTTPS_PROXY'].nil? %>
  chef_omnibus_url: http://www.getchef.com/chef/install.sh
  client_rb:
    http_proxy: <%= ENV['KITCHEN_HTTP_PROXY'] %>
    https_proxy: <%= ENV['KITCHEN_HTTPS_PROXY'].nil? ? ENV['KITCHEN_HTTP_PROXY'] : ENV['KITCHEN_HTTPS_PROXY'] %>
<% end %>


platforms:
#- name: centos-5.10
#  driver_config:
#    image: cpuguy83/centos
#    platform: centos
#    provision_command:
#      - curl -L https://www.opscode.com/chef/install.sh | bash
#      - yum -y install make gcc which bash tar cronie
- name: centos-6.4
  driver_config:
    image: learndocker/centos
    platform: centos
#    provision_command: &1
#      - curl -L https://www.opscode.com/chef/install.sh | bash
#      - rpm -ivh https://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
#      - yum makecache
#      - yum -y install ansible libselinux-python
#      - yum -y install make gcc which bash tar cronie
- name: centos-6.5
  driver_config:
    image: learndocker/centos
    platform: centos
#    provision_command: *1
- name: centos-7.0
  driver_config:
    image: centos:7
    platform: centos
    privileged: true
    provision_command: 
      - /usr/bin/systemctl enable sshd
    run_command: /usr/sbin/init
    privileged: true
    volume: '/sys/fs/cgroup:/sys/fs/cgroup'
# - name: yocto-ww18-15
#   driver_config:
#     image: yocto:ww18-15
#     platform: yocto
#     privileged: true
#     provision_command: 
#       - /usr/bin/systemctl enable sshd
#     run_command: /usr/sbin/init
#     privileged: true
#     volume: '/sys/fs/cgroup:/sys/fs/cgroup'
#    provision_command: *1
#- name: fedora-19
#  driver_config:
#    image: alexl/fedora-19
#    platform: fedora
#    provision_command: *1
## Precise Pangolin (LTS)
- name: ubuntu-12.04
  driver_config:
    provision_command: *1
#      - apt-get -y install apt-utils
#      - apt-get -y install software-properties-common python-software-properties
#      # - apt-get install tree && for f in $(echo $PATH | sed -e 's/:/ /g'); do tree $f; done
#      - add-apt-repository ppa:rquillo/ansible
#      - curl -L https://www.opscode.com/chef/install.sh | bash
#      - apt-get update
#      - apt-get -y install ansible python-selinux
#      - apt-get install -y build-essential bash debianutils dnsutils net-tools telnet tar cron
## Lucid Lynx (LTS) - EOL April 2015
- name: ubuntu-10.04
  driver_config:
    provision_command:
      - chmod 4755 /usr/bin/sudo
      - curl -L https://www.opscode.com/chef/install.sh | bash
      - curl -L https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh | bash
#      - apt-get -y install apt-utils
#      - apt-get -y install python-software-properties
      # - apt-get install tree && for f in $(echo $PATH | sed -e 's/:/ /g'); do tree $f; done
#      - add-apt-repository ppa:rquillo/ansible
#      - curl -L https://www.opscode.com/chef/install.sh | bash
#      - apt-get update
#      - apt-get -y install ansible python-selinux
#      - apt-get install -y build-essential bash debianutils dnsutils net-tools telnet tar cron
## Quantal EOL - 05/16/2014
# - name: ubuntu-12.10
#   driver_config:
#     provision_command: *1
## Raring EOL - 01/27/2014
#- name: ubuntu-13.04
#  driver_config:
#    provision_command: *1
## Saucy Salamander
- name: ubuntu-13.10
  driver_config:
    provision_command: *1
## Trusty Tahr LTS
- name: ubuntu-14.04
  driver_config:
    provision_command: *1
## Utopic Unicorn
#- name: ubuntu-14.10
#  driver_config:
#    provision_command: *1
