---
name: "Check label"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on: # yamllint disable-line rule:truthy
  # Use pull_request rather than pull_request_target to avoid exposing secrets
  # other than the ReadOnly GITHUB_TOKEN
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  check_label:
    uses: ansible/ansible-content-actions/.github/workflows/check_label.yaml@main
