---
# openwrt-base: entry point for handlers
# This should fix any weird opkg cache bugs
# Use this if you're seeing 0 packages for a repo,
- name: destroy opkg cache
  ansible.builtin.file:
    path: /var/opkg-lists
    force: true
    state: absent

- name: create opkg cache dir
  ansible.builtin.file:
    path: /var/opkg-lists
    force: true
    state: directory
    mode: "0755"

- name: opkg update
  ansible.builtin.command: opkg update
  check_mode: false
  register: opkg_update_result
  until: opkg_update_result is defined and opkg_update_result.rc == 0
  retries: 3
  delay: 1
  changed_when: opkg_update_result.rc == 0

- name: destroy apk cache
  ansible.builtin.file:
    path: /var/cache/apk
    force: true
    state: absent

- name: create apk cache dir
  ansible.builtin.file:
    path: /var/cache/apk
    force: true
    state: directory
    mode: "0755"

- name: apk update
  ansible.builtin.command: apk update
  check_mode: false
  register: apk_update_result
  until: apk_update_result is defined and apk_update_result.rc == 0
  retries: 3
  delay: 1
  changed_when: apk_update_result.rc == 0

# RAW command handlers for bootstrap steps
- name: RAW destroy opkg cache
  ansible.builtin.raw:
    rm -rf /var/opkg-lists
  register: opkg_destroy_cache_result
  changed_when: opkg_destroy_cache_result.rc == 0

- name: RAW create opkg cache dir
  ansible.builtin.raw:
    mkdir -p /var/opkg-lists
  register: opkg_mkdir_cache_result
  changed_when: opkg_mkdir_cache_result.rc == 0

- name: RAW opkg update
  ansible.builtin.raw: opkg update
  check_mode: false
  register: opkg_makecache_result
  until: opkg_makecache_result is defined and opkg_makecache_result.rc == 0
  retries: 3
  delay: 1
  changed_when: opkg_makecache_result.rc == 0

- name: RAW apk update
  ansible.builtin.raw: apk update
  check_mode: false
  register: apk_makecache_result
  until: apk_makecache_result is defined and apk_makecache_result.rc == 0
  retries: 3
  delay: 1
  changed_when: apk_makecache_result.rc == 0

- name: RAW uci commit
  ansible.builtin.raw: uci commit
  check_mode: false
  register: uci_commit_result
  until: uci_commit_result is defined and uci_commit_result.rc == 0
  changed_when: uci_commit_result.rc == 0

- name: RAW reboot
  ansible.builtin.raw: "reboot -d 2"
  check_mode: false
  register: reboot_result
  until: reboot_result is defined and reboot_result.rc == 0
  changed_when: reboot_result.rc == 0

- name: reload wifi
  ansible.builtin.raw: wifi
  register: openwrt_wifi_result
  changed_when: openwrt_wifi_result.rc == 0
  when: openwrt_wireless.changed
