---
# openwrt-base: entry point for handlers
# This should fix any weird opkg cache bugs
# Use this if you're seeing 0 packages for a repo,
- name: Destroy opkg cache
  ansible.builtin.file:
    path: /var/lib/opkg
    force: true
    state: absent

- name: Create opkg cache dir
  ansible.builtin.file:
    path: /var/lib/opkg
    force: true
    state: directory
    mode: "0755"

- name: Run opkg update
  ansible.builtin.command: opkg update
  check_mode: false
  register: opkg_makecache_result
  until: opkg_makecache_result is defined and opkg_makecache_result.rc == 0
  retries: 3
  delay: 1

# RAW command handlers for bootstrap steps
- name: RAW destroy opkg cache
  ansible.builtin.raw:
    rm -rf /var/lib/opkg

- name: RAW create opkg cache dir
  ansible.builtin.raw:
    mkdir -p /var/lib/opkg

- name: RAW opkg update
  ansible.builtin.raw: opkg update
  check_mode: false
  register: opkg_makecache_result
  until: opkg_makecache_result is defined and opkg_makecache_result.rc == 0
  retries: 3
  delay: 1
