---
# openwrt-dumbap-base: Tasks entry point. Called by main.yml

# Load a variable file based on the OS type, or a default if not found.
- name: Include vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: openwrt_base_sysctl_d is not defined

- name: Install sysct.d files
  ansible.builtin.template:
    src: templates/sysctl.d.j2
    dest: /etc/sysctl.d/{{ item.key }}.conf
    owner: root
    group: root
    mode: "0644"
  with_dict: "{{ openwrt_base_sysctl_d }}"
  when: openwrt_base_sysctl_d is defined
