---
# openwrt-base: entry point for tasks
#               Generally only include other file(s) and add tags here.

- name: "Run tasks: python-openwrt"
  ansible.builtin.import_tasks: python-openwrt.yml
  tags:
    - python-openwrt
    - openwrt_bootstrap
    - ansible_bootstrap
- name: "Run tasks: opkg-openwrt"
  ansible.builtin.import_tasks: opkg-openwrt.yml
  tags: opkg-openwrt
- name: "Run tasks: logrotate"
  ansible.builtin.import_tasks: logrotate.yml
  tags: logrotate-openwrt
- name: "Run tasks: crontabs"
  ansible.builtin.import_tasks: crontabs.yml
  tags:
    - crontabs-openwrt
    - openwrt-base-crontabs
- name: "Run tasks: kernel (sysctl.d)"
  ansible.builtin.import_tasks: kernel.yml
  tags:
    - kernel-openwrt
    - sysctl-openwrt
    - openwrt-base-kernel
    - openwrt-base-sysctl
